mate-desktop/atril

NEWS.gnome
TODO
backend/pdf/ev-poppler.cc
libdocument/ev-file-helpers.c
libview/ev-transition-animation.c
shell/ev-window.c

fix for https://bugs.debian.org/780500

[1.8] corrected bug tracker links everywhere

---

libview/ev-jobs.c

backport of https://github.com/mate-desktop/atril/pull/114 to 1.8 branch

[1.8] ev-jobs: don't forget to unlock the trylock'ed mutex

---

backend/dvi/dvi-document.c

fixes https://github.com/mate-desktop/atril/issues/164
regression has been introduced in https://github.com/mate-desktop/atril/commit/94dcb761b95ee54ef1f1512d59721932d75ffb7f

dvi: fix crash due to regression

---

data/org.mate.Atril.gschema.xml
shell/ev-application.c
shell/ev-application.h
shell/ev-metadata.c
shell/ev-window.c

This will fix https://github.com/mate-desktop/atril/issues/148 and other issues where a huge page cache is needed.
As always i backport some more stuff from evince which made adding the page cache commit for me easier.
Note, this is independent from gtk+ toolkit version.
@monsta @rootAvish 
please test

adding a page cache and a few other improvements

---

backend/dvi/dvi-document.c
configure.ac
cut-n-paste/toolbar-editor/egg-editable-toolbar.c
cut-n-paste/toolbar-editor/egg-editable-toolbar.h
cut-n-paste/toolbar-editor/egg-toolbar-editor.c
cut-n-paste/toolbar-editor/egg-toolbars-model.c
libdocument/ev-annotation.c
libdocument/ev-attachment.c
libdocument/ev-document-factory.c
libdocument/ev-document.c
libdocument/ev-document.h
libview/ev-document-model.c
libview/ev-print-operation.c
libview/ev-view.c
properties/ev-properties-view.c
shell/ev-annotation-properties-dialog.c
shell/ev-password-view.c
shell/ev-sidebar-annotations.c
shell/ev-window.c

I stopped here to fix more because the PR is huge enough.
@monsta @flexiondotorg @XRevan86 @lukefromdc
Please review

deprecation fixes and backports from evince

---

backend/comics/comics-document.c
backend/dvi/mdvi-lib/fontmap.c
backend/dvi/mdvi-lib/t1.c
backend/xps/xps-document.c
configure.ac
cut-n-paste/toolbar-editor/egg-toolbar-editor.c
libdocument/ev-document-misc.c
libdocument/ev-document-misc.h
libview/ev-document-model.c
libview/ev-document-model.h
libview/ev-view-presentation.c
libview/ev-view-private.h
libview/ev-view.c
shell/eggfindbar.c
shell/ev-sidebar-attachments.c
shell/ev-sidebar-bookmarks.c
shell/ev-window.c

@monsta @flexiondotorg 
Please test and review.

deprecation fixes and backports from evince round 2

---

backend/tiff/tiff-document.c
backend/tiff/tiff2ps.c
cut-n-paste/gimpcellrenderertoggle/gimpcellrenderertoggle.c
cut-n-paste/toolbar-editor/egg-toolbars-model.c
libview/ev-view-presentation.c
libview/ev-view-private.h
libview/ev-view.c
shell/ev-password-view.c
shell/ev-window.c

@monsta @flexiondotorg @lukefromdc
Please test and review.
Btw.
Adding the style classes is the real fix for https://github.com/mate-desktop/atril/issues/211

improvements and warnings

---

shell/ev-window.c

use GtkAbout instead of MateAbout

---

libdocument/ev-mapping-list.c
libdocument/ev-mapping-list.h
libview/Makefile.am
libview/ev-link-accessible.c
libview/ev-link-accessible.h
libview/ev-view-accessible.c
libview/ev-view-accessible.h
libview/ev-view-private.h
libview/ev-view.c
libview/ev-view.h

There are a lot more accessiblity commits to backport from upstream, but i will stop at this point to make the change not to huge.
Next step will be include carret navigation with atk commit, but this will come later.

first patch set of backporting accessiblity improvements from upstream

---

cut-n-paste/toolbar-editor/egg-editable-toolbar.c
cut-n-paste/toolbar-editor/egg-toolbar-editor.c
libview/ev-view.c
shell/ev-message-area.c
shell/ev-password-view.c
shell/ev-sidebar.c

deprecations

---

shell/ev-window.c

ev-window: don't use deprecated gtk_show_uri

---

libdocument/ev-document-misc.c
libview/ev-annotation-window.c
libview/ev-view.c

back to home ports

---

atril-document.h
help/reference/libdocument/libatrildocument-sections.txt
libdocument/Makefile.am
libdocument/ev-annotation.c
libdocument/ev-annotation.h
libdocument/ev-backends-manager.h
libdocument/ev-macros.h
libview/ev-annotation-window.c
shell/ev-annotation-properties-dialog.c
shell/ev-annotation-properties-dialog.h
shell/ev-sidebar-annotations.c
shell/ev-window.c

Back ports basicly from evince for the annotation window and sidebar

---

shell/ev-sidebar-thumbnails.c

Fixes https://github.com/mate-desktop/atril/issues/255
Please test.

sidebar thumbnails

---

libview/ev-view-private.h
libview/ev-view.c
libview/ev-view.h

Please test.
Some commits needs to test with a touchpad.

more backports

---

data/atril-previewer-ui.xml
data/atril-toolbar.xml
data/atril-ui.xml
libview/ev-view.c
libview/ev-view.h
libview/ev-web-view.c
libview/ev-web-view.h
previewer/ev-previewer-window.c
shell/ev-window.c

This will add zoom-reset function, please test.

Zoom reset

---

backend/epub/epub-document.c
libview/ev-jobs.c

- fixes thumbnails creation in sidebar
https://github.com/mate-desktop/atril/issues/187
- allow saving a copy

Epub thumbnails

---

libview/ev-pixbuf-cache.c
libview/ev-view-presentation.c
libview/ev-view.c

* https://git.gnome.org/browse/evince/commit/?id=a612f8
* https://git.gnome.org/browse/evince/commit/?id=90a258
* https://git.gnome.org/browse/evince/commit/?id=37c13b
Fixes #296

Render documents correctly on HiDPI displays

---

libview/ev-jobs.c

Fixes https://github.com/mate-desktop/atril/issues/308

libview: fix build without epub

---

libview/ev-page-accessible.c

Some more fixes from upstream.
Personal i couldn't reproduce what they fix because orca runs with or without them.
But i wouldn't be worse to use them.
@alexarnaud
Please test

A11y fixes

---

shell/ev-window.c

When annotating or filling a form in a document, this must be saved
as a different document as atril does not overwrite documents.
The user can expect to store the modified file in the same place
than the original document, except when the document lives in
a temporary directory (e.g. downloaded automatically with a web
browser), in whose case it must fallback to the Documents
directory (if set) or the the home directory.
Previously, atril assumed the latest directory used, or the place
where an image or attachment was stored last. Such behaviour is
confusing because the latest place opened might have no relation
with the document modified.
Fixes https://bugzilla.gnome.org/show_bug.cgi?id=767611
Adapted from https://gitlab.gnome.org/GNOME/evince/commit/319a6d49
Fixes #322

shell: Save document to the same path it was opened from

---

backend/comics/comicsdocument.atril-backend.in
configure.ac

Fixes https://github.com/mate-desktop/atril/issues/341
How to test:
See this sample **cbr** file without/with the PR
[testingcbr.zip](https://github.com/mate-desktop/atril/files/2550466/testingcbr.zip)

comics: support application/vnd.rar MIME type

---

cut-n-paste/zoom-control/ephy-zoom-action.c

[ephy-zoom-action] Avoid deprecated g_type_class_add_private

---

cut-n-paste/zoom-control/ephy-zoom-control.c

[ephy-zoom-control] Avoid deprecated g_type_class_add_private

---

shell/ev-window.c

This adds an accelerator to toggle the toolbar just like the side panel.
"T" was chosen as an accelerator as it is not used by any other action and it also fits with the action target's name.

Added accelerator 't' for toggling visibility of the toolbar.

---

libdocument/ev-document.c
libdocument/ev-document.h
shell/ev-window.c

show SyncTeX version in about dialog

---

cut-n-paste/smclient/eggsmclient.c
cut-n-paste/toolbar-editor/egg-toolbars-model.h
cut-n-paste/zoom-control/ephy-zoom-action.c
libdocument/ev-annotation.c
libdocument/ev-form-field.c
libdocument/ev-module.c
libdocument/ev-render-context.c
libmisc/ev-page-action-widget.c
libmisc/ev-page-action.c
libview/ev-jobs.c
libview/ev-pixbuf-cache.c
libview/ev-view.c
libview/ev-web-view.c
shell/eggfindbar.c
shell/ev-history.c
shell/ev-navigation-action-widget.c
shell/ev-navigation-action.c
shell/ev-open-recent-action.c

Fixes the warnings:
[Wredundant-decls.txt](https://github.com/mate-desktop/atril/files/3830457/Wredundant-decls.txt)

avoid redundant redeclarations

---

backend/pdf/ev-poppler.cc
shell/ev-sidebar-thumbnails.c

Memory issues

---

shell/ev-window.c

ev-window: expand the comment on about dialog

---

data/icons/16x16/mimetypes/Makefile.am
data/icons/22x22/mimetypes/Makefile.am
data/icons/24x24/mimetypes/Makefile.am
data/icons/32x32/mimetypes/Makefile.am
data/icons/scalable/actions/Makefile.am
data/icons/scalable/mimetypes/Makefile.am
git.mk

- Add the forgotten git.mk file
- Update some Makefile.am files

add git.mk to generate .gitignore

---

README.md

Use of submodule implies some commands before a compilation attempt.

Add compilation help

---

shell/ev-properties-dialog.c

Based on:
- https://github.com/mate-desktop/mate-terminal/commit/8d2eb0898154f2624e2ae34039169f307a3411a5
- https://github.com/mate-desktop/mate-terminal/commit/622e2d1272bf2d7a99d147482ae6a51b0a77f188

ev-properties-dialog: Add on_notebook_scroll_event

---

backend/epub/epub-document.c

Port of https://github.com/linuxmint/xreader/pull/334 to fix https://github.com/linuxmint/xreader/issues/274 that also affects atril.

Fix segfault on empty navMap

---

backend/epub/epub-document.c

- tab to spaces
- fix some indents

epub-document: improve code-style

---

libdocument/ev-file-helpers.c

https://github.com/GNOME/evince/commit/94171a14250f3713cb407b82b0df05cb52fc25b8

libdocument: remove _ev_g_mkdtemp function

---

po/POTFILES.in
shell/ev-sidebar.c

This PR also includes a po-update.

Accessibility: add button description

---

.build.yml
configure.ac

- fixes https://github.com/mate-desktop/atril/issues/582

support webkit2gtk-4.1and 4.0

---

data/atril.1

Add epub to man page

---

.travis.yml

ci: fix travis build failures caused by recent travis changes

---

README.md

* commit ce41df6 introduced libarchive for unpacking CBR comics

Update CBR library to libarchive in README.md

---

libview/ev-document-model.c
shell/ev-open-recent-action.c
shell/ev-window.c

Remove some build warnings, attempt to bring to code to a better state.

Clean some deprecations
