configure.ac
"thanks" to debian guys for removing 3.0 from testing repo
=> gtk3 build: use webkit2gtk-4.0 if 3.0 isn't available

configure.ac
code changes from https://github.com/GNOME/evince/commit/740263e84f812e069c25d32e6fbf40bec4c061e2 are already in, but the version bump isn't. fixed that.
=> require libgxps >= 0.2.0

backend/epub/epub-document.c
Once epub support has been implemented, atril crashes with all epubs.
Backtrace for 1.10.2+repack1-1 (Debian Stretch):
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd26d2700 (LWP 22276)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00007ffff755914e in ev_job_page_data_run (job=0x9e3850 [EvJobPageData]) at ev-jobs.c:762
#2  0x00007ffff755a85a in ev_job_thread_proxy (job=0x9e3850 [EvJobPageData]) at ev-job-scheduler.c:184
#3  0x00007ffff755a85a in ev_job_thread_proxy (data=<optimized out>) at ev-job-scheduler.c:217
#4  0x00007ffff14e1955 in g_thread_proxy (data=0x7fff84002280) at /build/glib2.0-VKSJTv/glib2.0-2.46.1/./glib/gthread.c:778
#5  0x00007ffff08690a4 in start_thread (arg=0x7fffd26d2700) at pthread_create.c:309
#6 …
=> Fix crash for epubs when accessibility is enabled

shell/ev-window.c
Should fix the pdf problems from #198, I'll see what I can do about the atril-thumbnailer crash.  @monsta @raveit65 please tell me if this works. I also heard and saw that no document thumbnails are being generated, webkit must have changed something in their screenshot API, because it's canceling all load requests. I'll see what can be done. Epub reloading... is not something I think is implemented correctly, so that would require work, but PDF's should work fine without any webkit mess ups.
=> Added conditions to check for non-existence of webview

backend/pdf/ev-poppler.cc
Poppler has a facility for case sensitive search, but it is not being used at the moment by atril. This patch calls the poppler search function with the right options.
=> Fix case sensitive searching for PDF

backend/comics/comics-document.c, backend/comics/comicsdocument.atril-backend.in, configure.ac
Fixes https://github.com/mate-desktop/atril/issues/225 (I hope so).
More info at https://bugzilla.gnome.org/770903.
@raveit65 @lukefromdc @sc0w guys, if you have any .cbr/.cbz files, please test it. This is one more issue caused by newer shared-mime-info versions...
=> comics: MIME type fixes

backend/comics/comics-document.c, backend/comics/comicsdocument.atril-backend.in, backend/djvu/djvudocument.atril-backend.in, configure.ac
more info at:
https://git.gnome.org/browse/evince/commit/?id=7850b986cf3225369170cdec545844b025bfd12e
This fixes https://bugs.debian.org/840324. Link to .djvu file for testing is also in that report.
@raveit65 @lukefromdc @sc0w guys, if you can, please test it on various (old and new) distro releases. The same .djvu file should now open fine with any version of shared-mime-info package (see the upstream commit for explanation).
=> djvu: support image/vnd.djvu+multipage MIME type

libview/ev-pixbuf-cache.c, libview/ev-view.c
For the displayed page, do not reload every time, should be displayed immediately
Tested successfully on Loongson 3A2000
with fedora25(mips64el distribution).
=> First page should not reloaded

shell/ev-window.c
Atril should respect if the user wants another toolbar-style than "both-horiz" by checking the "toolbar-style" key of the "org.mate.interface" schema in GSettings.
=> shell: Respect user's toolbar-style setting

configure.ac, libdocument/ev-document-misc.c, libdocument/ev-document-misc.h, libview/ev-annotation-window.c, libview/ev-pixbuf-cache.c, libview/ev-view.c, previewer/ev-previewer-window.c, shell/ev-window.c
This branch fixes the issue that linuxmint-devs only commit to their forked version of atril, instead commiting here and help out our project ;-)
For testing commit 2 you'll find an embedded form (pdf)  here https://github.com/linuxmint/xreader/issues/12#issuecomment-226129417
The HDPI commits i could only test with a non hdpi monitor.
@flexiondotorg 
Your Help is wanted :-)
So please test.
=> Back to home ports hdpi

shell/ev-window.c
GtkWindow catches keybindings for the menu items _before_ passing them to
the focused widget. This is unfortunate and means that pressing ctrl+Left
arrow, Ctrl+Right arrow on the search bar ends up turning the EvView
instead of moving around the text.
Here we override GtkWindow's handler to do the same things that it
does, but in the opposite order and then we chain up to the grand
parent handler, skipping gtk_window_key_press_event.
See https://bugzilla.gnome.org/show_bug.cgi?id=676040
inspired from https://git.gnome.org/browse/evince/commit/?id=70a2c0780b1b44acfa18f4762a3400b89eb123b5
fix rhbz https://bugzilla.redhat.com/show_bug.cgi?id=1513826
Please test
=> shell: forward accels to the focused widget

libdocument/ev-document-misc.c, libview/ev-view-presentation.c, libview/ev-view.c, shell/ev-window.c
This commit reverts:
https://github.com/mate-desktop/atril/commit/d9fffe2dc0e33d6777099c18635b7b75f54d3d35
And it applies an alternative to fix the deprecated functions:
gdk_screen_get_width
gdk_screen_get_height
=> WidthOfScreen and HeightOfScreen implementation

libview/ev-annotation-window.c
taken from:
https://github.com/GNOME/evince/commit/91ac78bc587eb2ac931136c9da9609b142410209
fixes the same problem as we had in stickynotes applet: when you try to select the text with mouse, the window is dragged instead.
=> libview: fix text selection with mouse in annotation window

libdocument/ev-document-misc.c, thumbnailer/Makefile.am, thumbnailer/atril-thumbnailer.c
- backend: Remove pixbuf backend
Evince is a document viewer, not an image viewer. Eog does the latter job
much better than evince ever could
- thumbnailer: Remove unused code
The code to overlay an icon is unused since commit (2005)
https://git.gnome.org/browse/evince/commit/?id=808285c
Please test.
=> Basic backports

shell/ev-window.c
To test the first commit:
- open truncated pdf (like [this one](https://bugzilla.redhat.com/show_bug.cgi?id=1536856#c20))
- press F5
- nothing should happen
Without the fix, you'll get to fullscreen (like with F11) and see some warnings in the terminal.
To test the second commit:
- open atril w/o documents or with truncated pdf
- press F11 to get to fullscreen
- Start Presentation button should be disabled
Without the fix, Start Presentation button is enabled. Clicking on it w/o documents makes atril crash. Clicking on it with truncated pdf leads to some warnings in the terminal.
=> Fix presentation actions

libview/ev-view-presentation.c
I see no changes in 'presentation' (F5) without deprecated code
=> presentation: avoid deprecated 'gtk_style_context_set_background'

libview/ev-view.c
Make sure not to move the caret in the wrong direction when restoring the visual line X offset, in case the visual and logical order is slightly different.
The algorithm used to move the cursor on the next line and restore the X position across lines works as follows:
1. Move `cursor_offset` to the next line by incrementing it until reaching a line break;
2. Find the Y coordinate corresponding to the new cursor_offset;
3. Find the text closest to the new Y coordinate and the previous X coordinate.
4. Move cursor_offset to the text at this new (X, Y) location.
The issue lies in step 3, which can find a position on a different line than expected in case several lines have a nearly the same Y position.
Evince references:
* https://gitlab.gnome.org/GNOME/evince/issues/889
* …
=> EvView: Fix cursor movement when logical and visual line order differs

backend/comics/comicsdocument.atril-backend.in, configure.ac
application/vnd.rar is for files with the .rar extension, application/vnd.comicbook-rar is the subtype for files with the .cbr extension.
This properly fixes #341
=> comics: fix incorrect mimetype which said to open and thumbnail all rar files

configure.ac, libview/ev-pixbuf-cache.c, libview/ev-view.c
such that hi-dpi conditionals aren't needed.
origin commit:
https://github.com/linuxmint/xreader/commit/df3cdc6
=> Bump Cairo version to 1.14.0

test/test1.py, test/test2.py, test/test3.py, test/test4.py, test/test5.py, test/test6.py, test/test7.py
May be it is the last part of mate-desktop is not working with python3.
This changes need to run with dogtail, it's a GUI test tool and automation framework, It is based on accessibility and I think it's amazing.
Please use the last release version of dogtail: https://gitlab.com/dogtail/dogtail/-/tags/DOGTAIL_0_9_11
Please configure with:
```
./configure --enable-tests
```
Run test use:
```
make check
```
=> migrate to python3 for test cases

backend/tiff/tiff-document.c
Apply /gitlab.gnome.org/GNOME/evince/commit/e02fe9170ad0ac2fd46c75329c4f1d4502d4a362
Fix  https://github.com/mate-desktop/atril/issues/386
=> Fix buffer overflow in backend/tiff-document.c

.travis.yml, cut-n-paste/toolbar-editor/egg-editable-toolbar.c, cut-n-paste/toolbar-editor/egg-editable-toolbar.h, cut-n-paste/toolbar-editor/egg-toolbar-editor.c, cut-n-paste/toolbar-editor/egg-toolbar-editor.h, cut-n-paste/zoom-control/ephy-zoom-action.c, libmisc/ev-page-action.c, previewer/ev-previewer-window.c, shell/ev-bookmark-action.c, shell/ev-navigation-action.c, shell/ev-open-recent-action.c, shell/ev-sidebar-bookmarks.c, shell/ev-window.c
Suppress GtkAction warnings which can't be fixed without removing icons from menus.
So, no need to let them spam our build logs, in result you overlook really important warnings.
Show those warnings in debian build only, to make one team member happy.
Please review.
=> Suppress GtkAction deprecation warnings

cut-n-paste/toolbar-editor/Makefile.am, libview/Makefile.am
Replace deprecated --header --body options
inspired by:
https://gitlab.gnome.org/GNOME/evince/commit/f6952c2
=> Fix build warning on marshalling

libdocument/ev-annotation.c
gdk_color_equal is simple enough to replace it with code inline
taken from:
https://gitlab.gnome.org/GNOME/evince/commit/1944b86
Please review.
=> document: Replace deprecated gdk_color_equal

shell/ev-window.c
See the issue report for a description of the bug. The root cause is
dereferencing of NULL pointers, specifically the priv->document member of
EvWindow structures when no document is loaded. This commit adds checks
for a NULL value of priv->document at all the points in the file
shell/ev-window.c where this pointer was previously dereferenced without
being checked.
This commit fixes the issue on the branch 1.20, which is the branch
mentioned in the issue report. A separate commit and pull request has
been submitted to fix this bug on the branch master.
Fixes 357 (https://github.com/mate-desktop/atril/issues/357)
=> Fix issue 357 on branch 1.20 - prevent segfaults when no document loaded

libview/ev-view-presentation.c, shell/ev-window.c
replace WidthOfScreen which works only with X11
inspired from:
https://gitlab.gnome.org/GNOME/evince/commit/40aa446
Please test.
=> shell: Use monitor instead of screen to determine window size

backend/tiff/tiff-document.c
The TIFFReadRGBAImageOriented function returns zero if it was unable to
read the image. Return NULL in this case instead of displaying
uninitialized memory.
This addresses CVE-2019-11459
Fixes #393 
upstream commit:
https://gitlab.gnome.org/GNOME/evince/commit/234f034a4
=> tiff: Handle failure from TIFFReadRGBAImageOriented

cut-n-paste/zoom-control/ephy-zoom-control.c, shell/ev-window.c
```
ephy-zoom-control.c:274:20: warning: variable ‘tool_item_class’ set but not used [-Wunused-but-set-variable]
274 |  GtkToolItemClass *tool_item_class;
|                    ^~~~~~~~~~~~~~~
--
ev-window.c:1390:10: warning: variable ‘page’ set but not used [-Wunused-but-set-variable]
1390 |  gint    page, n_pages;
|          ^~~~
```
=> remove -Wunused-but-set-variable warning

shell/ev-window.c
As requested in #365 to add accelerator for "Odd Pages Left" in dual page mode.
The character "o" was chosen as suggested, no other accelerator is bound to that character.
=> Fix for #365 ("Odd Pages Left" accelerator).

libview/ev-view.c
If view->pressed_button is left set, when the Drag and Drop operation completes, Atril will act as if it is still in a selection event.
Adapted from: https://gitlab.gnome.org/GNOME/evince/commit/92828bb797742e04aadbfdd62ba1da36837c37cf
=> libview: Reset `pressed_button` when starting Drag and Drop

.travis.yml
With this PR in the future we will see the "redundant redeclarations" warnings in the logs (warnings already fixed)
=> Travis CI: add '-Wredundant-decls' to 'CFLAGS' variable

libview/ev-pixbuf-cache.c, libview/ev-view.c
Fixes https://github.com/mate-desktop/atril/issues/404
First commit reverts https://github.com/mate-desktop/atril/pull/240 and fixes the huge memory consumption with max zoom, and second commit improve memory consumption in libview.
Note, you need to increase page-cache-size to reach higher zoom levels with this PR, default is 50MB.
```
gsettings get org.mate.Atril page-cache-size
200
```
With this setting a huge pdf doesn't use more than  ~1GB memory with 400% zoom.
Atril on master branch use more than 4.7 GB with same document, 50MB page-cache-size and 400% zoom, and a system with with 16 GB RAM can run out of memory when increasing page-cache-size. 
Note, on systems without using HIDPI the effect isn't so heavy.
Please test.
=> Fix mem when zooming

data/Makefile.am
Test:
```shell
$ sudo update-desktop-database /usr/share/applications
```
Diff:
```shell
$ ./autogen --prefix=/usr && make
$ cp data/atril.desktop data/atril.desktop.old
(changes)
$ ./autogen --prefix=/usr && make
$ diff data/atril.desktop.old data/atril.desktop
229c229
< X-MATE-Bugzilla-Version=@VERSION@
---
> X-MATE-Bugzilla-Version=1.23.1
233c233
< MimeType=@ATRIL_MIME_TYPES@
---
> MimeType=application/pdf;application/x-bzpdf;application/x-gzpdf;application/x-xzpdf;application/postscript;application/x-bzpostscript;application/x-gzpostscript;image/x-eps;image/x-bzeps;image/x-gzeps;application/x-dvi;application/x-bzdvi;application/x-gzdvi;image/vnd.djvu;image/vnd.djvu+multipage;image/tiff;application/x-cbr;application/x-cbz;application/x-cb7;application/x-cbt;application/vnd.comicbook+zip …
```
=> Fix atril.desktop file

backend/pdf/ev-poppler.cc, configure.ac, libdocument/ev-annotation.c, libdocument/ev-annotation.h, libdocument/ev-attachment.c, libdocument/ev-attachment.h, libdocument/ev-document-info.h, libdocument/ev-document-misc.c, libdocument/ev-document-misc.h, properties/ev-properties-view.c, shell/ev-window.c
GTime is defined to always be a signed 32-bit integer, it will
overflow in the year 2038.
Test: Modified time = 2147617954 > 2^31
```shell
$ exiftool -all=  file.pdf
$ touch -t 203801201732.34 file.pdf
$ LANG=C gio info -a time::modified mozilla.pdf
uri: file:///home/robert/mozilla.pdf
attributes:
time::modified: 2147617954
$ LANG=C date -d "@2147617954" +"%c"
Wed Jan 20 17:32:34 2038
$ exiftool -all:all file.pdf
ExifTool Version Number         : 11.70
File Name                       : file.pdf
Directory                       : .
File Size                       : 375 kB
File Modification Date/Time     : 2038:01:20 17:32:34+01:00
File Access Date/Time           : 2038:01:20 17:32:34+01:00
File Inode Change Date/Time     : 2020:01:20 21:42:32+01:00
File Permissions                : …
```
=> Fix year 2038 issue with signed 32-bit integers

shell/ev-window.c
See https://github.com/mate-desktop/atril/pull/434#discussion_r379825415
=> Use int64_t for g_date_time_to_unix even word size is 32-bit wide

backend/dvi/mdvi-lib/dviread.c
```
dviread.c:1104:1: warning: ‘inline’ is not at beginning of declaration [-Wold-style-declaration]
1104 | static int inline move_vertical(DviContext *dvi, int amount)
| ^~~~~~
dviread.c:1127:1: warning: ‘inline’ is not at beginning of declaration [-Wold-style-declaration]
1127 | static int inline move_horizontal(DviContext *dvi, int amount)
| ^~~~~~
dviread.c:1150:1: warning: ‘inline’ is not at beginning of declaration [-Wold-style-declaration]
1150 | static void inline fix_after_horizontal(DviContext *dvi)
| ^~~~~~
```
=> dviread: ‘inline’ is not at beginning of declaration

.build.yml, backend/epub/Makefile.am
We can see more build warnings in atril with this change
=> Travis CI: build with --enable-cxx-warnings=maximum

backend/epub/epub-document.c
```
epub-document.c:502:25: warning: unused variable ‘children’ [-Wunused-variable]
502 |     xmlNodePtr topchild,children ;
|                         ^~~~~~~~
--
epub-document.c:1333:9: warning: unused variable ‘archive_dir’ [-Wunused-variable]
1333 |  gchar* archive_dir = epub_document->tmp_archive_dir;
|         ^~~~~~~~~~~
--
epub-document.c:1512:16: warning: unused variable ‘class’ [-Wunused-variable]
1512 |     xmlAttrPtr class =  xmlNewProp(link,(xmlChar*)"class",(xmlChar*)"night");
|                ^~~~~
epub-document.c:1511:16: warning: unused variable ‘rel’ [-Wunused-variable]
1511 |     xmlAttrPtr rel = xmlNewProp(link,(xmlChar*)"rel",(xmlChar*)"alternate stylesheet");
|                ^~~
epub-document.c:1510:16: warning: unused variable ‘href’ [-Wunused-variable]
1510 | …
```
=> epub-document: Remove unused-variable warning

backend/epub/epub-document.c, shell/ev-window.c
Fixes the build warnings:
```
ev-window.c:6379:1: warning: function 'menubar_deactivate_cb' is not needed and will not be emitted [-Wunneeded-internal-declaration]
menubar_deactivate_cb (GtkWidget *menubar,
^
epub-document.c:946:1: warning: function 'check_add_page_numbers' is not needed and will not be emitted [-Wunneeded-internal-declaration]
check_add_page_numbers(linknode *listdata, contentListNode *comparenode)
^
```
=> ev-window/epub-document: remove unused functions

backend/dvi/mdvi-lib/fontmap.c, backend/epub/epub-document.c
```
epub-document.c:438:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
438 | xml_free_doc();
| ^~~~~~~~~~~~
epub-document.c:575:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
575 | xml_free_doc()
| ^~~~~~~~~~~~
--
fontmap.c:648:13: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
648 | static void init_static_encoding()
|             ^~~~~~~~~~~~~~~~~~~~
```
=> Remove strict-prototypes warning

backend/comics/comics-document.c, backend/epub/minizip/unzip.c, properties/ev-properties-view.c, shell/ev-sidebar-thumbnails.c, shell/main.c
Fixes the warnings:
```
backend/comics/comics-document.c:767:21: style: Condition 'bytes<=0' is always true [knownConditionTrueFalse]
backend/epub/minizip/unzip.c:603:25: style: Condition 'unz_copyright[0]!=' '' is always false [knownConditionTrueFalse]
properties/ev-properties-view.c:197:33: style: Condition 'text' is always true [knownConditionTrueFalse]
shell/ev-sidebar-thumbnails.c:598:7: style: Condition '!loading_icon' is always true [knownConditionTrueFalse]
shell/main.c:115:6: style: Condition '!error' is always true [knownConditionTrueFalse]
```
=> Fix cppcheck [knownConditionTrueFalse] warnings

backend/djvu/djvu-text-page.c
Fixes the warnings:
```
backend/djvu/djvu-text-page.c:46:31: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
g_strjoin (delimit & 2 ? "\n" :
^
backend/djvu/djvu-text-page.c:47:28: style: Clarify calculation precedence for '&' and '?'. [clarifyCalculation]
delimit & 1 ? " " : NULL,
^
```
https://en.cppreference.com/w/c/language/operator_precedence
=> djvu-text-page: Fix cppcheck [clarifyCalculation] warnings

configure.ac, libdocument/Makefile.am, libdocument/ev-document.c, libview/ev-view-private.h, libview/ev-view.c, shell/ev-window.c
This is still work in progress. The code still needs to be disabled
in the C code.
Comments are welcome, I am a total idiot when it comes to autotools :-P.
=> Make synctex an optional dependency

backend/pdf/ev-poppler.cc
```
ev-poppler.cc:1384:1: warning: no previous declaration for 'GdkPixbuf* pdf_document_images_get_image(EvDocumentImages*, EvImage*)' [-Wmissing-declarations]
1384 | pdf_document_images_get_image (EvDocumentImages *document_images,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> ev-poppler: remove warning about no previous declaration

shell/ev-sidebar-attachments.c
When looking at a document that has attachments, the attachment window only opens up a very small portion of the sidebar up at the top.  Looking at the source code for another document viewer from another project *cough* evince *cough* I found you needed to have a call to gtk_box_pack_start () in order to have it fill out the sidebar.  Here's a pull request that fixes the issue.  Tested on Debian 10, works.
=> Make sure attachments window fills entire sidebar

libview/ev-pixbuf-cache.c
Test: select any text in a document
```
ev-pixbuf-cache.c: In function 'get_selection_colors':
/usr/include/glib-2.0/glib/gmacros.h:811:63: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
811 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
|                                                               ^
ev-pixbuf-cache.c:644:21: note: in expansion of macro 'CLAMP'
644 |         text->red = CLAMP ((guint) (fg.red * 65535), 0, 65535);
|                     ^~~~~
/usr/include/glib-2.0/glib/gmacros.h:811:30: warning: conversion from 'unsigned int' to 'guint16' {aka 'short unsigned int'} may change value [-Wconversion]
811 | #define CLAMP(x, low, high)  (((x) > (high)) ? (high) : (((x) < (low)) ? (low) : (x)))
| …
```
=> ev-pixbuf-cache: Remove -Wtype-limits warnings

backend/epub/epub-document.c, cut-n-paste/toolbar-editor/egg-toolbars-model.c
Fix for missing xmlDocGetRootElement() check problem in #485
=> check return value of xmlDocGetRootElement call if is NULL

shell/ev-sidebar-attachments.c
Fixes a runtime warning caused by
https://github.com/mate-desktop/atril/commit/70f42da
See https://github.com/mate-desktop/atril/pull/476#issuecomment-667701035
for more info.
=> ev-sidebar-attachments: do not add add a Gtk_Container

shell/ev-window.c
```
ev-view-presentation.c:255:28: warning: conversion from 'gdouble' {aka 'double'} to 'guint' {aka 'unsigned int'} may change value [-Wfloat-conversion]
255 |     g_timeout_add_seconds (duration,
|                            ^~~~~~~~
```
=> ev-window: fix interval (guint milliseconds) in g_timeout_add_full

backend/pdf/ev-poppler.cc
```
ev-poppler.cc:1093:9: warning: enumeration value 'POPPLER_ACTION_RESET_FORM' not handled in switch [-Wswitch]
1093 |  switch (action->type) {
|         ^
```
=> ev-poppler: 'POPPLER_ACTION_RESET_FORM' not handled in switch [-Wswitch]

backend/epub/epub-document.c, help/reference/libdocument/Makefile.am, help/reference/libview/Makefile.am, help/reference/shell/Makefile.am
Closes #495
```
(atril:2235): Gtk-WARNING **: 14:13:45.580: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```
=> epub backend: Escape link text to display & in index content

shell/ev-application.c, shell/main.c
=> Support non-X11 windowing systems

backend/ps/ev-spectre.c
test #506
before
```
$ atril ~/Documents/ptc40.ps
(libspectre) ghostscript reports: undefined -21
Segmentation fault (core dumped)
```
after
```
$ atril ~/Documents/ptc40.ps
(libspectre) ghostscript reports: undefined -21
** (atril:325985): WARNING **: 21:08:44.687: libspectre reports: render error
Segmentation fault (core dumped)
```
=> ps backend: do not silence the warnings when rendering the page

libview/ev-jobs.c, libview/ev-pixbuf-cache.c
closes #506
based on https://github.com/GNOME/evince/commit/f93a84c015a53f6fa89f2af04ad004631d8b7442
=> Check whether the document page failed to render

backend/dvi/mdvi-lib/dviread.c, libview/ev-view-presentation.c
```
atril.make.log:dviread.c:617:16: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
atril.make.log-  617 |  if(np.density < 0)
atril.make.log-      |                ^
--
atril.make.log:ev-view-presentation.c:428:11: warning: comparison of unsigned expression in '< 0' is always false [-Wtype-limits]
atril.make.log-  428 |  if (page < 0 || page >= ev_document_get_n_pages (pview->document))
atril.make.log-      |           ^
```
=> Remove warning -Wtype-limits

configure.ac, data/Makefile.am, data/atril.appdata.xml.in.in, po/POTFILES.in, properties/Makefile.am, properties/libatril-properties-page.caja-extension.desktop.in.in, shell/ev-window.c
Test:
```
$ grep homepage data/atril.appdata.xml
<url type="homepage">https://mate-desktop.org</url>
$ grep Website properties/libatril-properties-page.caja-extension
Website=https://mate-desktop.org
$ grep PACKAGE_URL config.h
#define PACKAGE_URL "https://mate-desktop.org"
```
- Fix build error (po/POTFILES.in):
```
make[6]: *** No rule to make target '../../../properties/libatril-properties-page.caja-extension.desktop.in', needed by 'atril.pot-update'.  Stop.
make[6]: Leaving directory '/home/robert/atril/atril-1.25.0/_build/sub/po'
make[5]: *** [Makefile:589: update-po] Error 2
make[5]: Leaving directory '/home/robert/atril/atril-1.25.0/_build/sub/po'
make[4]: *** [Makefile:555: distdir] Error 2
make[4]: Leaving directory '/home/robert/atril/atril-1.25.0/_build/sub/po'
make[3]: *** …
```
=> build: Use PACKAGE_URL variable

shell/ev-window.c
```
ev-window.c:6437:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
ev-window.c:6438:9: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
ev-window.c:6439:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
ev-window.c:6440:9: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} [-Wmissing-field-initializers]
ev-window.c:6441:2: warning: missing initializer for field ‘accelerator’ of ‘GtkActionEntry’ {aka ‘const struct _GtkActionEntry’} …
```
=> ev-window: missing initializer for a field of ‘GtkActionEntry’

libdocument/Makefile.am, libview/Makefile.am
When building atril with `--enable-introspection` and slibtool (https://dev.midipix.org/cross/slibtool) it fails.
```
rdlibtool --mode=execute ldd /tmp/atril/libdocument/tmp-introspectx_ramcgd/AtrilDocument-1.5.0
rdlibtool: lconf: {.name="libtool"}.
rdlibtool: fdcwd: {.fdcwd=AT_FDCWD, .realpath="/tmp/atril/libdocument"}.
rdlibtool: lconf: fstatat(AT_FDCWD,".",...) = 0 {.st_dev = 45, .st_ino = 78493}.
rdlibtool: lconf: openat(AT_FDCWD,"libtool",O_RDONLY,0) = -1 [ENOENT].
rdlibtool: lconf: openat(AT_FDCWD,"../",O_DIRECTORY,0) = 3.
rdlibtool: lconf: fstat(3,...) = 0 {.st_dev = 45, .st_ino = 77854}.
rdlibtool: lconf: openat(3,"libtool",O_RDONLY,0) = 4.
rdlibtool: lconf: found "/tmp/atril/libtool".
/tmp/atril/libdocument/tmp-introspectx_ramcgd/.libs/AtrilDocument-1.5.0: error while loading …
```
=> introspection: Fix bogus --library arguments.

shell/ev-sidebar-links.c
Commit adapted for atril, picked up from:
https://gitlab.gnome.org/GNOME/evince/-/commit/c3de8e75d6d0920478af210ba19a2d94b0734917
Credits to Benjamin Berg <bberg@redhat.com>
| For large documents the linear search for the first link that is on a
| certain page is really slow. Because of this scrolling becomes slow
| whenever the page changes.
|
| Replace the linear search with a search in a binary tree populated with
| the first link on each page and the corresponding GtkTreePath. This way
| a specialized binary tree lookup can be used to find the closest
| matching link and select that in the treeview.
|
| https://bugzilla.gnome.org/show_bug.cgi?id=779614
=> ev-sidebar-links: Optimize reverse link lookup for a page

shell/ev-window.c
A WebKit processes should only be created when the user actually requests to open a file type requiring WebKit to be processed.
Fixes #529
=> ev-window.c: only create a EvWebView if needed

backend/epub/epub-document.c
Add a null check as well.
Fixes segfault due to xml_parse_children_of_node() getting passed a NULL pointer (nav).
example file:
https://github.com/IDPF/epub3-samples/releases/download/20170606/cc-shared-culture.epub
ref:
https://help.apple.com/itc/booksassetguide/en.lproj/itc0f175a5b9.html#apdd3c4c6d1c0904
https://idpf.org/epub/301/spec/epub-contentdocs-20140626.html#sec-xhtml-nav
https://github.com/linuxmint/xreader/commit/7689e36ee9941cce8e8ac75306bccdd91af58485
=> epub: Fix index loading for certain documents - look for epub:type instead of epub:id

backend/epub/epub-document.c
=> epub: add fallback for malformed epub files in check_mime_type

cut-n-paste/toolbar-editor/egg-toolbars-model.c
libxml 2.12.0 reorganized headers, resulting in xmlParseFile and xmlIndentTreeOutput no longer being in scope.
Let’s add the proper includes containing the symbols.
=> Fix build with libxml2 2.12

backend/epub/epub-document.c
This commit also fixes an incorrect `sizeof` call detected by AddressSanitizer.
Closes #599
- Note: My testing occurred against the 1.26 branch
- I verified the EPUB from #599 can now be opened with Atril
- I verified that AddressSanitizer did not report any memory issues when loading the EPUB
=> epub: Avoid crash when index list has extraneous entry

backend/epub/epub-document.c
closes https://github.com/mate-desktop/atril/issues/603
=> fix a incompatible pointer type warning for gcc14

shell/ev-application.c
*Put a missed instance of gdk_x11_screen_get_screen_number behind x11-only selectors
=> Wayland: stop segfaults on some systems

configure.ac
Fix #613
See also https://bugs.launchpad.net/ubuntu/+source/atril/+bug/1873998
=> Fix .cbr mimetype

meson.build
Without this the setup can accept a mate-desktop version that cannot be built against, leading to build failures rather than setup bailout.
=> meson: Fix mate-desktop-2.0 dependency

libview/meson.build
=> meson: Fix libview GIR namespace
